export type TimestampStyle = 'seconds' | 'worded' | 'beats'
export type CameraStyle = 'operator' | 'motion-first' | 'directorial' | 'minimal'

export interface ModelAdapter {
  id: string
  name: string
  vendor: string
  providerHint: string
  maxChars: number
  idealChars: [number, number]
  supportsNegative: boolean
  timestampStyle: TimestampStyle
  cameraStyle: CameraStyle
  structure: 'linear-paragraphs' | 'structured-blocks' | 'shot-list' | 'single-flow'
  accent: string
  notes: string
  active: boolean
  compilerVersion: string
  /** Exact clip durations this model can generate in one pass (seconds). */
  clipLengths: number[]
  /** Pre-selected clip duration when the user doesn't choose. */
  defaultClipLength: number
}

export const MODEL_ADAPTERS: ModelAdapter[] = [
  {
    id: 'veo',
    name: 'Veo 3.1',
    vendor: 'Google',
    providerHint: 'Google',
    maxChars: 2600,
    idealChars: [900, 2200],
    supportsNegative: false,
    timestampStyle: 'seconds',
    cameraStyle: 'operator',
    structure: 'linear-paragraphs',
    accent: '#4A90FF',
    notes: 'Flowing director-to-camera paragraphs, explicit seconds, audio-aware. Generates 4, 6 or 8s clips.',
    active: true,
    compilerVersion: 'veo-c 3.3',
    clipLengths: [4, 6, 8],
    defaultClipLength: 8,
  },
  {
    id: 'flow-omni',
    name: 'Flow · Omni Flash 1.1',
    vendor: 'Google Flow',
    providerHint: 'Google Flow',
    maxChars: 2400,
    idealChars: [700, 2000],
    supportsNegative: false,
    timestampStyle: 'seconds',
    cameraStyle: 'operator',
    structure: 'linear-paragraphs',
    accent: '#7C9BFF',
    notes: 'Google Flow Omni Flash 1.1: fixed 4 / 6 / 8 / 10-second clips per generation. Conversational editing — keep instructions imperative and scene-complete.',
    active: true,
    compilerVersion: 'omni-c 1.1',
    clipLengths: [4, 6, 8, 10],
    defaultClipLength: 10,
  },
  {
    id: 'kling',
    name: 'Kling 2.5',
    vendor: 'Kuaishou',
    providerHint: 'Kuaishou',
    maxChars: 2200,
    idealChars: [500, 1500],
    supportsNegative: true,
    timestampStyle: 'worded',
    cameraStyle: 'motion-first',
    structure: 'structured-blocks',
    accent: '#22D3EE',
    notes: 'Motion-first phrasing with explicit negative prompt line. 5s or 10s generations.',
    active: true,
    compilerVersion: 'kling-c 2.9',
    clipLengths: [5, 10],
    defaultClipLength: 10,
  },
  {
    id: 'runway',
    name: 'Runway Gen-4.5',
    vendor: 'Runway',
    providerHint: 'Runway',
    maxChars: 1200,
    idealChars: [300, 950],
    supportsNegative: false,
    timestampStyle: 'beats',
    cameraStyle: 'directorial',
    structure: 'single-flow',
    accent: '#34D399',
    notes: 'Short, dense, camera-move-led; avoid heavy timestamp notation. 5s or 10s generations (Turbo extends).',
    active: true,
    compilerVersion: 'rw-c 2.0',
    clipLengths: [5, 10],
    defaultClipLength: 10,
  },
  {
    id: 'sora',
    name: 'Sora 2',
    vendor: 'OpenAI',
    providerHint: 'OpenAI',
    maxChars: 3000,
    idealChars: [900, 2400],
    supportsNegative: false,
    timestampStyle: 'seconds',
    cameraStyle: 'operator',
    structure: 'linear-paragraphs',
    accent: '#F59E0B',
    notes: 'World-consistency language, physical continuity. Standard generations are 4 / 8 / 12s (Pro extends to 20s+).',
    active: true,
    compilerVersion: 'sora-c 2.2',
    clipLengths: [4, 8, 12],
    defaultClipLength: 8,
  },
  {
    id: 'hailuo',
    name: 'MiniMax H3 (Hailuo)',
    vendor: 'MiniMax',
    providerHint: 'MiniMax',
    maxChars: 1800,
    idealChars: [400, 1300],
    supportsNegative: true,
    timestampStyle: 'worded',
    cameraStyle: 'minimal',
    structure: 'structured-blocks',
    accent: '#F472B6',
    notes: 'Subject-first, compact, expressive motion. H3 generates 5–15s clips at up to 2K with native stereo audio.',
    active: true,
    compilerVersion: 'h3-c 1.0',
    clipLengths: [5, 10, 15],
    defaultClipLength: 10,
  },
  {
    id: 'seedance-2-5',
    name: 'Seedance 2.5',
    vendor: 'ByteDance',
    providerHint: 'ByteDance / Dreamina',
    maxChars: 2600,
    idealChars: [700, 2000],
    supportsNegative: true,
    timestampStyle: 'seconds',
    cameraStyle: 'directorial',
    structure: 'structured-blocks',
    accent: '#FB7185',
    notes: 'Native single-take up to 30s with audio, 4K. 4–30s per generation — ideal for multi-cut recreations in one pass.',
    active: true,
    compilerVersion: 'sd-c 2.5',
    clipLengths: [5, 10, 15, 20, 30],
    defaultClipLength: 10,
  },
  {
    id: 'seedance-2',
    name: 'Seedance 2.0',
    vendor: 'ByteDance',
    providerHint: 'ByteDance / Dreamina',
    maxChars: 2200,
    idealChars: [600, 1600],
    supportsNegative: true,
    timestampStyle: 'seconds',
    cameraStyle: 'directorial',
    structure: 'structured-blocks',
    accent: '#F97066',
    notes: 'Previous flagship: up to 15s single-pass. Pacing-aware, handles internal cuts well.',
    active: true,
    compilerVersion: 'sd-c 2.0',
    clipLengths: [5, 10, 15],
    defaultClipLength: 10,
  },
  {
    id: 'seedance-mini',
    name: 'Seedance 2.0 Mini / Fast',
    vendor: 'ByteDance',
    providerHint: 'ByteDance / Dreamina',
    maxChars: 1600,
    idealChars: [400, 1200],
    supportsNegative: true,
    timestampStyle: 'worded',
    cameraStyle: 'minimal',
    structure: 'structured-blocks',
    accent: '#FDA29B',
    notes: 'Fast + cheap tier. 5s or 10s clips, shorter prompt tolerance — keep the kit tight.',
    active: true,
    compilerVersion: 'sd-c 2.0m',
    clipLengths: [5, 10],
    defaultClipLength: 5,
  },
  {
    id: 'wan-3',
    name: 'Wan 3.0',
    vendor: 'Alibaba',
    providerHint: 'Alibaba Tongyi',
    maxChars: 2400,
    idealChars: [600, 1800],
    supportsNegative: true,
    timestampStyle: 'seconds',
    cameraStyle: 'operator',
    structure: 'structured-blocks',
    accent: '#38BDF8',
    notes: 'Native up to 30s 1080p with in-pass audio; any length from ~2–30s per pass. Likes descriptive scene-scaping.',
    active: true,
    compilerVersion: 'wan-c 3.0',
    clipLengths: [5, 10, 15, 30],
    defaultClipLength: 10,
  },
  {
    id: 'wan-2-5',
    name: 'Wan 2.5',
    vendor: 'Alibaba',
    providerHint: 'Alibaba Tongyi',
    maxChars: 2000,
    idealChars: [500, 1500],
    supportsNegative: true,
    timestampStyle: 'worded',
    cameraStyle: 'operator',
    structure: 'structured-blocks',
    accent: '#7DD3FC',
    notes: 'Reliable 5s / 10s generations with audio. Compact cinematic blocks.',
    active: true,
    compilerVersion: 'wan-c 2.5',
    clipLengths: [5, 10],
    defaultClipLength: 10,
  },
  {
    id: 'other',
    name: 'Other / Auto',
    vendor: 'Generic',
    providerHint: 'Generic',
    maxChars: 2200,
    idealChars: [500, 1800],
    supportsNegative: true,
    timestampStyle: 'seconds',
    cameraStyle: 'directorial',
    structure: 'structured-blocks',
    accent: '#8B90B5',
    notes: 'Balanced generic cinematic prompt that works nearly anywhere. 4–10s clips.',
    active: true,
    compilerVersion: 'gen-c 2.1',
    clipLengths: [4, 5, 6, 8, 10],
    defaultClipLength: 10,
  },
]

export const getModel = (id: string): ModelAdapter =>
  MODEL_ADAPTERS.find((m) => m.id === id) ?? MODEL_ADAPTERS[0]

/** Snap any requested duration to the closest length the model can generate. */
export const snapClipLength = (adapter: ModelAdapter, seconds: number): number =>
  adapter.clipLengths.reduce((best, l) =>
    Math.abs(l - seconds) < Math.abs(best - seconds) ? l : best,
  adapter.defaultClipLength)

export const BRAND_COLORS: Record<string, string> = {
  'Google': '#4A90FF',
  'Google Flow': '#7C9BFF',
  'Kuaishou': '#22D3EE',
  'Runway': '#34D399',
  'OpenAI': '#F59E0B',
  'MiniMax': '#F472B6',
  'ByteDance': '#FB7185',
  'Alibaba': '#38BDF8',
  'Generic': '#8B90B5',
}
